package dreammungz.enums;

/*
@author 황승주
@since 2022. 09. 11.
*/

public enum JobName {
    KING, ASTRONAUT, ATHLETE, DOCTOR, POLICE, CHEF, IDOL,
    DEVELOPER, MUNGPIA, TEACHER, JUDGE, MYSTERIOUS_THIEF, TRAVELER,
    ARTIST, SCIENTIST, JANITOR, REPORTER, BUILDING_OWNER,
    VOCALIST, SCULPTOR, UNKNOWN_AUTHOR, YOUTUBER, BODYGUARD,
    FORTUNE_TELLER, THIEF, PHILOSOPHER, FARMER, JOBLESS
}
