const statusName = {
  //스탯
  STOUTNESS: "튼튼함",
  CLEVER: "영리함",
  QUICK: "재빠름",
  INTUITION: "직감",
  CHARISMA: "용기",
  POPULARITY: "인기",
  SENSIBILITY: "감수성",
  FOOTWORK: "발재주",
  VOICE: "목청",
  WEALTH: "재력",
  //직업
  KING: "왕",
  ASTRONAUT: "우주비행사",
  ATHLETE: "운동선수",
  DOCTOR: "의사",
  POLICE: "경찰",
  CHEF: "요리사",
  IDOL: "아이돌",
  DEVELOPER: "개발자",
  MUNGPIA: "멍피아",
  TEACHER: "선생님",
  JUDGE: "판사",
  MYSTERIOUS_THIEF: "괴도",
  TRAVELER: "여행자",
  ARTIST: "화가",
  SCIENTIST: "과학자",
  JANITOR: "청소부",
  REPORTER: "기자",
  BUILDING_OWNER: "건물주",
  VOCALIST: "성악가",
  SCULPTOR: "조각가",
  UNKNOWN_AUTHOR: "무명작가",
  YOUTUBER: "유튜버",
  BODYGUARD: "보디가드",
  FORTUNE_TELLER: "점술사",
  THIEF: "도둑",
  PHILOSOPHER: "철학자",
  FARMER: "농부",
  JOBLESS: "백수",
  //털모양
  ORIGINAL: "직모",
  CURLY: "곱슬",
  //등급
  NORMAL: "노멀",
  RARE: "레어",
  EPIC: "에픽",
  UNIQUE: "유니크",
  LEGENDARY: "레전더리",
  //색상
  WHITE: "하양",
  BLACK: "검정",
  BROWN: "갈색",
  RED: "빨강",
  YELLOW: "노랑",
  GREEN: "초록",
  BLUE: "파랑",
  PINK: "분홍",
  ORANGE: "주황",
  PURPLE: "보라",
  GOLD: "황금",
  RAINBOW: "무지개",
  // 얼굴
  BASIC: "기본",
  ANGRY: "화남",
  SAD: "눈물",
  HALF: "반눈",
  BEAN: "콩눈",
  ZZANG: "짱구",
  SCAR: "사납",
  WINK: "윙크",
  GLASSES: "안경",
  SHY: "샤이",
}

const findKOR = (status) => {
  return statusName[status]
}

export default findKOR
